In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
img = cv2.imread("./1.aidaishu.jpg",cv2.IMREAD_REDUCED_COLOR_4)
cv2.imshow("p_1",img)
cv2.waitKey(0)          #--->注意，是waitKey  K是大写，如果是小写的话会卡住动不了
cv2.destroyAllWindows()    #--->注意，是destroy！！！

In [10]:
img.shape     #下面的三个值对应 h w c

(1008, 756, 3)

In [13]:
img_1 = cv2.imread("./1.aidaishu.jpg")     #--->BGR三个颜色对应的亮度矩阵
img

array([[[ 42,  77,  43],
        [ 42,  77,  43],
        [ 43,  78,  44],
        ...,
        [208, 202, 203],
        [209, 203, 204],
        [209, 203, 204]],

       [[ 42,  77,  43],
        [ 42,  77,  43],
        [ 45,  78,  44],
        ...,
        [208, 202, 203],
        [209, 203, 204],
        [209, 203, 204]],

       [[ 42,  77,  43],
        [ 44,  77,  43],
        [ 45,  78,  44],
        ...,
        [208, 202, 203],
        [209, 203, 204],
        [209, 203, 204]],

       ...,

       [[133, 120, 112],
        [133, 120, 112],
        [133, 120, 112],
        ...,
        [172, 177, 180],
        [172, 177, 180],
        [172, 175, 179]],

       [[130, 118, 112],
        [130, 118, 112],
        [130, 118, 112],
        ...,
        [172, 177, 180],
        [172, 175, 179],
        [172, 175, 179]],

       [[130, 118, 112],
        [130, 118, 112],
        [130, 118, 112],
        ...,
        [172, 175, 179],
        [172, 175, 179],
        [174, 175, 179]]

In [16]:
img_2 = cv2.imread("./1.aidaishu.jpg",cv2.IMREAD_GRAYSCALE)     #灰度图对应的矩阵
img

array([[ 63,  63,  64, ..., 203, 204, 204],
       [ 63,  63,  64, ..., 203, 204, 204],
       [ 63,  63,  64, ..., 203, 204, 204],
       ...,
       [119, 119, 119, ..., 177, 177, 176],
       [118, 118, 118, ..., 177, 176, 176],
       [118, 118, 118, ..., 176, 176, 176]], dtype=uint8)

In [18]:
type(img)

numpy.ndarray

In [19]:
img.size

12192768

In [7]:
vc = cv2.VideoCapture(0)
if vc.isOpened():
    open,frame = vc.read()    # --->会返回两个值，第一个是布尔类型的值， 第二个是返回来的每一帧的图像
else:
    open = False
while open:
    ret,frame = vc.read()
    if frame is None:
        break
    if ret == True:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        cv2.imshow("result",gray)
        if cv2.waitKey(10) & 0xFF == 27:
            break
vc.release()
cv2.destroyAllWindows()

In [ ]:
b,g,r = cv2.split(img)   #--->将图片按BGR三个颜色来切片

In [6]:
r

array([[ 43,  43,  44, ..., 203, 204, 204],
       [ 43,  43,  44, ..., 203, 204, 204],
       [ 43,  43,  44, ..., 203, 204, 204],
       ...,
       [112, 112, 112, ..., 180, 180, 179],
       [112, 112, 112, ..., 180, 179, 179],
       [112, 112, 112, ..., 179, 179, 179]], dtype=uint8)

In [7]:
r.shape

(4032, 3024)

In [8]:
img = cv2.merge((b,g,r))     #切片完了还可以重新装回去
img.shape

(4032, 3024, 3)

In [10]:
cur_img = img.copy()
cur_img [:,:,0] = 0
cur_img [:,:,1] = 0       #BGR三种颜色分别对应的0，1，2，想要切其他颜色的话就以此类推
cv2.imshow('R',cur_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
边界填充

In [ ]:
数值计算 

In [ ]:
import cv2
img = cv2.imread("./1.aidaishu.jpg")

In [ ]:
img_1 = img + 10     #--->如果这个数超过了255，那么这个值会变成超过255的值-255
img [:5,:,0]

In [ ]:
img_1 [:5,:,0]