## 什么是图像轮廓

<font size = 3>之前学的 sobel算子、scharr算子、laplasian算子、canny边缘检测，这些都是检测图像中边缘线条的，检测出来的是图像的边缘，而非图像轮廓，要加以区分<br>
边缘检测主要是通过一些手段检测数字图像中明暗变化剧烈（即梯度变化比较大）像素点，偏向于图像中像素点的变化<br>轮廓检测指检测图像中的对象边界，更偏向于关注上层语义对象，主要用来分析物体的形态，比如物体的周长和面积等。可以说边缘包括轮廓。边缘主要是作为图像的特征使用，比如可以用边缘特征可以区分脸和手，而轮廓则是一个很好的图像目标的外部特征</font>

## 查找轮廓函数

<font size = 4>   contours, hierarchy = cv2.findContours(img, mode, method) </font>

### 解释

<font size = 3> 
img:要做轮廓检测的图像，必须是8位单通道二值图像。所以，一般情况下我们都是将图像处理为二值图像后再将其作为参数传入。在很多情况下，我们是预先对图像进行阈值分割或者边缘检测处理(比如经过Canny、拉普拉斯等边缘检测算子处理过的二值图像)，在得到满意的二值图像后再作为参数传入使用，这样效果会更好</font>


<font size = 3>
mode:    mode: 轮廓检索模式。决定了轮廓的提取方式：<br>
　　cv2.RETR_EXTERNAL: 只检测最外面的轮廓<br>
　　cv2.RETR_LIST: 检索所有的轮廓，并将其保存到一条链表当中。对检测到的轮廓不建立等级关系<br>
　　cv2.RETR_CCOMP：检索所有轮廓并将它们组织成两级层次结构。顶层是各部分的外部边界，第二层是空洞的边界。<br>
　　cv2.RETR_TREE：检索所有轮廓，并建立一个等级树结构的轮廓，就是重构嵌套轮廓的整个层次。<br>
　　说明：一般情况下我们只用第4种模式，因为第4种模式是检测所有的轮廓并且把这些轮廓按层次保存成一个树结构，后面如果我们有需要直接调用即可。<br>
</font>

<font size = 3> method： 轮廓逼近方法，就是如何表达轮廓，意思就是我是用线表示轮廓呢，还是简单点用2个点就表示了一条线的轮廓：<br>
　　cv2.CHAIN_APPROX_NONE:(保存全部的轮廓的点的坐标) 以Freeman链码的方式输出轮廓。意思就是我存储了所有的轮廓点，就是相连两个点的像素位置差不超过1，我可以用完整的线条来表示轮廓，就是我可以画出一个完整的轮廓。<br>
　　cv2.CHAIN_APPROX_SIMPLE：(只保存轮廓的角的点的坐标)压缩水平方向、垂直方向、对角线方向的元素，只保留该方向的终点坐标。比如一个矩形只要用4个点来保存轮廓信息即可。因为要保存信息太多了，内存计算起来都是负担，我们就用4个点表示一个矩形轮廓吧。同理，如果是一个多边形，我们就输出这个多边形的顶点序列吧。  </font>

<font size = 3>contours：是返回的轮廓。这个轮廓是一个数组。<br>
hierarchy：是轮廓的层次信息，就是mode参数决定的返回的轮廓数据的组织结构   </font>

### demo:

In [1]:
import cv2
import numpy as np
img = cv2.imread('./1.aidaishu.jpg')
img = cv2.resize(img,(378,504))
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
thresh,binary = cv2.threshold(gray,160,255,cv2.THRESH_BINARY)
contours,hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
print(type(contours))
print(type(hierarchy))
print(hierarchy)
cv2.imshow('contours',binary)
cv2.waitKey()
cv2.destroyAllWindows()

<class 'tuple'>
<class 'numpy.ndarray'>
[[[  1  -1  -1  -1]
  [  2   0  -1  -1]
  [  3   1  -1  -1]
  [  4   2  -1  -1]
  [  5   3  -1  -1]
  [  6   4  -1  -1]
  [  7   5  -1  -1]
  [  8   6  -1  -1]
  [  9   7  -1  -1]
  [ 10   8  -1  -1]
  [ 11   9  -1  -1]
  [ 12  10  -1  -1]
  [ 13  11  -1  -1]
  [ 14  12  -1  -1]
  [ 15  13  -1  -1]
  [ 16  14  -1  -1]
  [ 17  15  -1  -1]
  [ 18  16  -1  -1]
  [ 19  17  -1  -1]
  [ 20  18  -1  -1]
  [ 21  19  -1  -1]
  [ 22  20  -1  -1]
  [ 24  21  23  -1]
  [ -1  -1  -1  22]
  [ 25  22  -1  -1]
  [ 26  24  -1  -1]
  [ 27  25  -1  -1]
  [ 29  26  28  -1]
  [ -1  -1  -1  27]
  [ 30  27  -1  -1]
  [ 31  29  -1  -1]
  [ 32  30  -1  -1]
  [ 33  31  -1  -1]
  [ 34  32  -1  -1]
  [ 35  33  -1  -1]
  [ 36  34  -1  -1]
  [ 37  35  -1  -1]
  [ 38  36  -1  -1]
  [ 39  37  -1  -1]
  [ 40  38  -1  -1]
  [ 41  39  -1  -1]
  [ 42  40  -1  -1]
  [ 43  41  -1  -1]
  [ 44  42  -1  -1]
  [ 45  43  -1  -1]
  [ 46  44  -1  -1]
  [150  45  47  -1]
  [ 48  -1  -1  46]


## 绘制轮廓

### cv2.drawContours(image, contours, contourIdx, color, thickness=None, lineType=None, hierarchy=None, maxLevel=None, offset=None)

<font size = 3>第一个参数是指明在哪幅图像上绘制轮廓；image为三通道才能显示轮廓<br>
第二个参数是轮廓本身，在Python中是一个list<br>
第三个参数指定绘制轮廓list中的哪条轮廓，如果是-1，则绘制其中的所有轮廓。后面的参数很简单。其中thickness表明轮廓线的宽度，如果是-1（cv2.FILLED），则为填充模式   </font>

<font size = 3> 绘制轮廓会直接修改原图，如果想让原图保持不变的话就需要copy一份  </font>

In [2]:
img_copy_1 = img.copy()
img_copy_1 = cv2.drawContours(img_copy_1,contours,-1,(0,0,255),2)
cv2.imshow('contours',img_copy_1)
cv2.waitKey() 
cv2.destroyAllWindows()

## 计算轮廓面积

In [3]:
area = cv2.contourArea(contours[1])
print("area:",area)

area: 34.0


## 计算轮廓周长

In [4]:
perimeter = cv2.arcLength(contours[1],closed = True)
print("perimeter:",perimeter)

perimeter: 25.656854152679443


## 多边形逼近与突包(无法使用)

<font size = 3>
cv2.approxPolyDP(curve,epsilon,closed[,approxCurve])<br>
Curve:要画的轮廓；<br>
Epsilon:精度（精度越高，数据量越大）；<br>
Closed:是否闭合；<br>
approxCurve:类型应与输入曲线的类型匹配（如果closed=True，则近似的曲线也是closed=True）
</font>

In [5]:
approx = cv2.approxPolyDP(contours[0],3,closed = True)
print(approx)
cv2.drawContours(img_copy_1,[approx],0,(0,255,0),2)
cv2.imshow('approx',img_copy_1)
cv2.waitKey()
cv2.destroyAllWindows()

[[[377 483]]

 [[372 503]]

 [[377 503]]]


6什么吊东西都画不出来